# Configuration:
exclude: ["CNAME", "README.md"]
permalink: /:year/:month/:day/:title
excerpt_separator: "<!-- break -->"

# Metadata:
title: Passion Talks 2015
tagline: Connecting Work and Faith
author:
  name: Passion Talks
pti_url: "http://passiontalks.org"

# Navigation menu items. (Note that these a preceded by some fixed
# items coded directly in _includes/navbar.html .)
navigation:
  - label: Call for Participation
    url: "/call"
  - label: Submit a Talk
    url: "/submit"
  - label: Register
    url: "/register"
#  - label: Schedule
#    url: "/"
#  - label: Travel
#    url: "/"
  - label: About
    url: "/about"
  - label: Vision
    url: "/vision"

# Content configuration defaults:
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: true
      highlight_first: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sidebar: true
      highlight_first: false
